CREATE TABLE
    IF NOT EXISTS available_cars (
        id int AUTO_INCREMENT PRIMARY KEY,
        sold boolean,
        brand text,
        model text,
        body text,
        exteriorColor text,
        interiorColor text,
        driveType text,
        transmission text,
        price int,
        buildYear int,
        milage int,
        topSpeed float,
        acceleration float,
        liters float,
        shape char(1),
        cylinders int,
        aspiration text,
        eMotor int,
        hp int,
        torque int,
        displacement int,
        weight int,
        width float,
        length float,
        height float,
        wheelBase float,
        description text
    );
